/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#565e74',
        'investment-blue': '#197FE3',
        'on-primary': '#ffffff',
        'warning-amber': '#F59F00',
        'on-surface-variant': '#45464d',
        'primary': '#000000',
        'outline-variant': '#c6c6cd',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#000000',
        'on-tertiary-container': '#2585e9',
        'primary-container': '#131b2e',
        'secondary': '#735c00',
        'slate-900': '#0F172A',
        'on-primary-container': '#7c839b',
        'gold-leaf': '#D4AF37',
        'error': '#ba1a1a',
        'success-green': '#22CB22',
        'surface-variant': '#e0e3e5',
        'on-secondary-container': '#745c00',
        'outline': '#76777d',
        'tertiary-container': '#001c3a',
        'surface-bright': '#f7f9fb',
        'background': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'inverse-surface': '#2d3133',
        'surface-container-highest': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'surface': '#f7f9fb',
        'primary-fixed': '#dae2fd',
        'surface-container': '#eceef0',
        'on-surface': '#191c1e',
        'error-container': '#ffdad6',
        'on-background': '#191c1e',
        'on-primary-fixed': '#131b2e',
        'zinc-500': '#71717A',
        'inverse-on-surface': '#eff1f3',
        'secondary-container': '#fed65b',
        'on-tertiary-fixed': '#001c3a',
        'tertiary-fixed': '#d4e3ff',
        'secondary-fixed': '#ffe088',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'inverse-primary': '#bec6e0',
        'primary-fixed-dim': '#bec6e0',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed-variant': '#004786',
        'secondary-fixed-dim': '#e9c349',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#a6c8ff',
        'surface-tint': '#565e74',
        'on-secondary-fixed-variant': '#574500',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'gutter': '24px',
        'base': '8px',
        'margin-desktop': '80px',
        'section-gap': '120px',
        'margin-mobile': '20px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'luxury': '0 10px 40px -10px rgba(0,0,0,0.05), 0 20px 25px -5px rgba(0,0,0,0.02)',
        'layers': '0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03)',
        'soft': '0 10px 25px -5px rgba(0,0,0,0.02), 0 8px 10px -6px rgba(0,0,0,0.02)',
      },
    },
  },
  plugins: [],
}
